FROM golang:1.6.4-alpine
MAINTAINER Aleksei Shaikhaleev <nimdraug.sael@gmail.com>

RUN apk update && \
  apk add git

COPY . /go/src/github.com/nimdraugsael/locator

RUN cd /go/src/github.com/nimdraugsael/locator && go get -d -v && go install

